README.md
=> docs(update): minor

dist/.nitro/dev/index.mjs, dist/.nitro/nitro.json, src/server/routes/projects.get.ts
=> feat(project): angular macedonia

src/styles.css
=> docs(update): minor more

src/app/pages/(home).page.ts
=> fix(home): styling margin filtering

dist/.nitro/nitro.json, src/app/pages/(home).page.ts
=> second deploy to see changes live = must look into why this is necessary

dist/.nitro/dev/index.mjs, dist/.nitro/nitro.json, src/server/routes/projects.get.ts
=> fix(project): analogjs info update

CONTRIBUTING.md, src/app/components/footer.component.ts, src/app/pages/fqa.page.ts
=> feat(fqa, footer): infor update, temp github icon

src/styles.css
=> feat(styling): making dark theme coloring a tiny bit lighter

src/app/pages/(home).page.ts
=> feat(home): primeng icon added for projects

src/app/pages/fqa.page.ts
=> second one to get api changes

dist/.nitro/nitro.json, src/app/pages/(home).page.ts, src/styles.scss
=> feat(home): primeng tooltip added

src/app/pages/(home).page.ts
=> minor styling

dist/.nitro/dev/index.mjs, dist/.nitro/nitro.json, src/app/components/footer.component.ts, src/app/pages/about.page.ts
closes #
- updating the repo info
=> feat(readme, about): updated info

src/app/pages/about.page.ts, src/app/pages/fqa.page.ts
=> about update

src/app/pages/about.page.ts
=> about better

src/app/pages/(home).page.ts
=> fix(home): p-card missing class

index.html
=> fix(sitewide): default og:image path

dist/.nitro/nitro.json, src/app/pages/(home).page.ts, src/app/pages/about.page.ts, src/app/pages/fqa.page.ts, src/styles.scss
=> feat(pages): responsiveness and chevrondownicon

src/app/pages/(home).page.ts
=> fix(home): unused imports

dist/.nitro/dev/index.mjs, dist/.nitro/nitro.json, src/app/pages/about.page.ts
=> fix(about): about page update

.github/FUNDING.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, src/app/pages/(home).page.ts
closes #
- my username update 
=> username update
